<?php

namespace EtoxMicrome\ToxicEndpointBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ToxicEndpointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ToxicEndpointRepository extends EntityRepository
{
}
