<?php

namespace EtoxMicrome\MeshTermBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MeshTermRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeshTermRepository extends EntityRepository
{
    public function getEntityIdFromName($entityName)
    {
        $message="llega a getEntityIdFromName dentro de repositorio MeshTerm";
        ldd($message);
        return $valToSearch;
    }
}
