<?php

namespace EtoxMicrome\MeshTermBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MeshTerm2AbstractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeshTerm2AbstractRepository extends EntityRepository
{
}
