<?php

namespace EtoxMicrome\Entity2DocumentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Compound2Cyp2DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Compound2Cyp2DocumentRepository extends EntityRepository
{
    public function getAllRelationsFromSentenceId($sentenceId)
    {
        $sql="SELECT c2c2d
            FROM EtoxMicromeEntity2DocumentBundle:Compound2Cyp2Document c2c2d
            WHERE c2c2d.sentenceId = (:sentenceId)
            ";

        //ld($sql);
        $query = $this->_em->createQuery($sql);
        $query->setParameter("sentenceId", $sentenceId);
        return $query;

    }
}
