<?php

namespace EtoxMicrome\Entity2DocumentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Compound2Cyp2DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Compound2Cyp2DocumentRepository extends EntityRepository
{
    public function getAllRelationsFromSentenceId($sentenceId)
    {
        $sql="SELECT c2c2d
            FROM EtoxMicromeEntity2DocumentBundle:Compound2Cyp2Document c2c2d
            WHERE c2c2d.sentenceId = (:sentenceId)
            ";

        //ld($sql);
        $query = $this->_em->createQuery($sql);
        $query->setParameter("sentenceId", $sentenceId);
        return $query;

    }
    public function updateCompound2Cyp2DocumentCuration($compound2Cyp2DocumentId, $action)
    {
        //Explain for the homologous updateEntity2DocumentCuration at Entity2DocumentRepository
        /*Here we get the entity2Document and the action to take for the curation value.
        $action can be check or cross.
        If $action==check, then we have to add one to the curation field of the Entity2Document register
        If $action==cross, then we have to substract one to the curation field of the Entity2Document register

        After that, taking into account the curation value, we have to generate the html to render inside the curation
        */

        //ld($entity2DocumentId);
        //ldd($action);

        $em = $this->getEntityManager();
        $compound2Cyp2Document=$em->getRepository('EtoxMicromeEntity2DocumentBundle:Compound2Cyp2Document')->findOneById($compound2Cyp2DocumentId);
        if (!$compound2Cyp2Document) {
            throw $this->createNotFoundException(
                "Cannot curate this Compound2Cyp2Document $compound2Cyp2DocumentId"
            );
        }
        else{
            $curation=$compound2Cyp2Document->getCuration();
            if ($action=="check"){
                $compound2Cyp2Document->setCuration($curation + 1);
            }elseif($action=="cross"){
                $compound2Cyp2Document->setCuration($curation - 1);
            }
            $em->flush();
            $curationReturn=$compound2Cyp2Document->getCuration();
            return($curationReturn);
        }
        return ($curationReturn);
    }

    public function countCompound2CypRelations($compoundName)
    {
        $message="inside countCompound2CypRelations";
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT COUNT(c2t2d.id) FROM EtoxMicromeEntity2DocumentBundle:Compound2Cyp2Document c2t2d where c2t2d.compoundName= :compoundName');
        $query->setParameter("compoundName", $compoundName);
        $count = $query->getSingleScalarResult();

        return $count;

    }

    public function findCompounds2Cyp2DocumentFromCyp($cyp, $dictionaryCompounds)
    {
        //Attention! This function returns 2 arrays. First with keys = compoundName and values= number of times (weight) of this relation
        //Second array have a dictionary with values = compoundName and values = dictionaryRelations
        //dictionaryRelations is an asociative array with keys = patternRelation and values = number of times that this type of relation has been established between this compoundName and the Marker
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT c2c2d
            FROM EtoxMicromeEntity2DocumentBundle:Compound2Cyp2Document c2c2d
            WHERE c2c2d.cypsMention = :cyp
        ');
        $consulta->setParameter('cyp', $cyp);
        $arrayCompounds2Cyp2Documents = $consulta->execute();
        //We search the arrayCompounds2Cyp2Documents and only return the components that are present in the $dictionaryCompounds argument (compounds that already are part of the interaction network)
        $tmpArray=array();//Associative array with the keys="compoundName" and the values="number of times present"
        $tmpArrayTypeRelations=array();//Associative array with the keys="compoundName" and the values=dictionaryRelations
        foreach($arrayCompounds2Cyp2Documents as $compound2Cyp2Document){
            $compoundName=$compound2Cyp2Document->getCompoundName();
            $patternRelation=$compound2Cyp2Document->getPatternRelation();
            if(array_key_exists($compoundName, $dictionaryCompounds)){
                if (array_key_exists($compoundName, $tmpArray)){
                    $tmpArray[$compoundName]=$tmpArray[$compoundName]+1;
                    //If there is already a tmpArray with this compoundName, there should be already a $tmpArrayTypeRelations that we should update with this new or repeated patternRelation
                    $dictionaryRelations=$tmpArrayTypeRelations[$compoundName];
                    if (array_key_exists($patternRelation, $dictionaryRelations)){
                        //We update the entry
                        $dictionaryRelations[$patternRelation]=$dictionaryRelations[$patternRelation]+1;
                        $tmpArrayTypeRelations[$compoundName]=$dictionaryRelations;
                    }else{
                        //We create a new entry
                        $dictionaryRelations=$tmpArrayTypeRelations[$compoundName];
                        $dictionaryRelations[$patternRelation]=1;
                        $tmpArrayTypeRelations[$compoundName]=$dictionaryRelations;
                    }
                }else{
                    $dictionaryRelations=array();
                    $tmpArray[$compoundName]=1;
                    $dictionaryRelations[$patternRelation]=1;
                    $tmpArrayTypeRelations[$compoundName]=$dictionaryRelations;
                }
            }
        }
        $returnArray=array($tmpArray,$tmpArrayTypeRelations);
        return ($returnArray);
    }
}
