<?php

namespace EtoxMicrome\Entity2DocumentBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * Entity2DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Entity2DocumentRepository extends EntityRepository
{
   public function getValToSearch($field)
    {
        switch ($field) {
            case "hepatotoxicity":
                $valToSearch="hepval";
                break;
            case "cardiotoxicity":
                $valToSearch="cardval";
                break;
            case "nephrotoxicity":
                $valToSearch="nephval";
                break;
            case "phospholipidosis":
                $valToSearch="phosval";
                break;
        }
        return $valToSearch;
    }

    public function getOrderBy($orderBy, $valToSearch)
    {
        switch ($orderBy) {
            case "score":
                $orderBy=$valToSearch;
                break;
            case "pattern":
                $orderBy="patternCount";
                break;
            case "rule":
                $orderBy="ruleScore";
                break;
            case "term":
                $orderBy="hepTermVarScore";
                break;
        }
        return $orderBy;
    }

    public function getEntity2DocumentFromField($field, $typeOfEntity, $arrayEntityName, $source, $orderBy)
    {
        return $this->getEntity2DocumentFromFieldDQL($field, $typeOfEntity, $arrayEntityName, $source, $orderBy)->getResult();
    }

    public function getEntity2DocumentFromFieldDQL($field, $entityType, $arrayEntityName, $source, $orderBy)
    {//("hepatotoxicity","pubmed","CompoundDict",arrayEntityId)
        $valToSearch=$this->getValToSearch($field);//"i.e hepval, embval... etc"
        //We have to create a query that searchs all over the entityIds inside the $arrayEntityId
        $orderBy=$this->getOrderBy($orderBy, $valToSearch);
        if ($source=="all"){//Depending on the source we add or not the d.kind=source parameter to the query

            //$sql="SELECT e2d,d
            //    FROM EtoxMicromeEntity2DocumentBundle:Entity2Document e2d
            //    JOIN e2d.document d
            //    WHERE e2d.name IN (:arrayEntityName)
            //    AND e2d.qualifier = :entityType
            //    AND d.$orderBy is not null
            //    ORDER BY d.$orderBy DESC
            //    ";
            $sql="SELECT e2d
                    FROM EtoxMicromeEntity2DocumentBundle:Entity2Document e2d
                    WHERE e2d.name IN (:arrayEntityName)
                    AND e2d.qualifier = :entityType
                    AND e2d.$orderBy is not null
                    ORDER BY e2d.$orderBy DESC
                ";

            $query = $this->_em->createQuery($sql);
            $query->setParameter("arrayEntityName", $arrayEntityName);
            $query->setParameter('entityType', $entityType);
        }else{
            $sql="SELECT e2d,d
                FROM EtoxMicromeEntity2DocumentBundle:Entity2Document e2d
                JOIN e2d.document d
                WHERE e2d.name IN (:arrayEntityName)
                AND e2d.qualifier = :entityType
                AND d.$orderBy is not null
                AND d.kind = :source
                ORDER BY d.$orderBy DESC
                ";


            $query = $this->_em->createQuery($sql);
            $query->setParameter("arrayEntityName", $arrayEntityName);
            $query->setParameter('entityType', $entityType);
            $query->setParameter('source', $source);
        }
        /*
        $rawSql = $query->getSql();
        print_r(array(
            'parameters' => $query->getParameters(),
        ));
        ldd($rawSql);
        */
        return $query;
    }


    public function getCompound2Term2DocumentFromField($field, $typeOfEntity, $arrayEntityName, $orderBy)
    {
        return $this->getCompound2Term2DocumentFromFieldDQL($field, $typeOfEntity, $arrayEntityName, $orderBy)->getResult();
    }

    public function getCompound2Term2DocumentFromFieldDQL($field, $entityType, $arrayEntityName, $orderBy)
    {//("hepatotoxicity","pubmed","CompoundDict",arrayEntityId)
        $valToSearch=$this->getValToSearch($field);//"i.e hepval, embval... etc"
        //We have to create a query that searchs all over the entityIds inside the $arrayEntityId
        $orderBy=$this->getOrderBy($orderBy, $valToSearch);
        ldd($orderBy);
        $sql="SELECT c2t2d
            FROM EtoxMicromeEntity2DocumentBundle:Compound2Term2Document c2t2d
            WHERE c2t2d.compoundName IN (:arrayEntityName)
            ORDER BY c2t2d.$orderBy desc
            ";

        $query = $this->_em->createQuery($sql);
        $query->setParameter("arrayEntityName", $arrayEntityName);
        return $query;

    }

    public function getCompound2TermRelations($field, $typeOfEntity, $arrayEntityName, $source, $orderBy)
    {
        return $this->getCompound2TermRelationsDQL($field, $typeOfEntity, $arrayEntityName, $source, $orderBy)->getResult();
    }

    public function getCompound2TermRelationsDQL($field, $entityType, $arrayEntityName, $source, $orderBy)
    {//("hepatotoxicity","pubmed","CompoundDict",arrayEntityId)
        $valToSearch=$this->getValToSearch($field);//"i.e hepval, embval... etc"
        //We have to create a query that searchs all over the entityIds inside the $arrayEntityId
        if($orderBy=="term"){
            $orderBy="term asc";
        }
        elseif($orderBy=="relationType"){
            $orderBy="relationType asc";
        }
        elseif($orderBy=="compoundName"){
            $orderBy="compoundName asc";
        }
        elseif($orderBy=="relationScore"){
            $orderBy="relationScore desc";
        }elseif($orderBy=="curation"){
            $orderBy="curation desc";
        }else{
            $orderBy=$this->getOrderBy($orderBy, $valToSearch);
            if ($orderBy=="hepval"){
                $orderBy="relationScore asc";
            }
        }
        if($source=="all"){
            $sql="SELECT c2t2d
            FROM EtoxMicromeEntity2DocumentBundle:Compound2Term2Document c2t2d
            WHERE c2t2d.compoundName IN (:arrayEntityName)
            ORDER BY c2t2d.$orderBy, c2t2d.hepval desc
            ";
            $query = $this->_em->createQuery($sql);
            $query->setParameter("arrayEntityName", $arrayEntityName);
        }else{
            $sql="SELECT c2t2d, d
                FROM EtoxMicromeEntity2DocumentBundle:Compound2Term2Document c2t2d
                JOIN c2t2d.document d
                WHERE c2t2d.compoundName IN (:arrayEntityName) AND d.kind = :source
                ORDER BY c2t2d.$orderBy , c2t2d.hepval desc
            ";
            $query = $this->_em->createQuery($sql);
            $query->setParameter("arrayEntityName", $arrayEntityName);
            $query->setParameter("source", $source);
        }
        return $query;

    }

    public function getTerm2CompoundRelations($field, $typeOfEntity, $arrayEntityName, $source, $orderBy)
    {
        return $this->getTerm2CompoundRelationsDQL($field, $typeOfEntity, $arrayEntityName, $source, $orderBy)->getResult();
    }

    public function getTerm2CompoundRelationsDQL($field, $entityType, $arrayEntityName, $source, $orderBy)
    {//("hepatotoxicity","pubmed","CompoundDict",arrayEntityId)
        //Same method as getCompound2TermRelationsDQL but we are searching for terms instead of compounds!!  REFACTOR IT!!!!!
        $valToSearch=$this->getValToSearch($field);//"i.e hepval, embval... etc"
        //We have to create a query that searchs all over the entityIds inside the $arrayEntityId
        if($orderBy=="term"){
            $orderBy="term asc";
        }
        elseif($orderBy=="relationType"){
            $orderBy="relationType asc";
        }
        elseif($orderBy=="compoundName"){
            $orderBy="compoundName asc";
        }
        elseif($orderBy=="relationScore"){
            $orderBy="relationScore desc";
        }elseif($orderBy=="curation"){
            $orderBy="curation desc";
        }else{
            $orderBy=$this->getOrderBy($orderBy, $valToSearch);
            if ($orderBy=="hepval"){
                $orderBy="relationScore desc";
            }
        }
        if($source=="all"){
            $sql="SELECT c2t2d
            FROM EtoxMicromeEntity2DocumentBundle:Compound2Term2Document c2t2d
            WHERE c2t2d.term IN (:arrayEntityName)
            ORDER BY c2t2d.$orderBy, c2t2d.hepval desc
            ";
            $query = $this->_em->createQuery($sql);
            $query->setParameter("arrayEntityName", $arrayEntityName);
        }else{
            $sql="SELECT c2t2d, d
                FROM EtoxMicromeEntity2DocumentBundle:Compound2Term2Document c2t2d
                JOIN c2t2d.document d
                WHERE c2t2d.term IN (:arrayEntityName) AND d.kind = :source
                ORDER BY c2t2d.$orderBy, c2t2d.hepval desc
            ";
            $query = $this->_em->createQuery($sql);
            $query->setParameter("arrayEntityName", $arrayEntityName);
            $query->setParameter("source", $source);
        }

        return $query;

    }

    public function getCompound2Cytochrome2DocumentFromField($field, $typeOfEntity, $arrayEntityName, $orderBy)
    {
        return $this->getCompound2Cytochrome2DocumentFromFieldDQL($field, $typeOfEntity, $arrayEntityName, $orderBy)->getResult();
    }

    public function getCompound2Cytochrome2DocumentFromFieldDQL($field, $entityType, $arrayEntityName, $orderBy)
    {//("hepatotoxicity","pubmed","CompoundDict",arrayEntityId)
        $valToSearch=$this->getValToSearch($field);//"i.e hepval, embval... etc"
        //We have to create a query that searchs all over the entityIds inside the $arrayEntityId
        $orderBy=$this->getOrderBy($orderBy, $valToSearch);
        $sql="SELECT c2c2d
            FROM EtoxMicromeEntity2DocumentBundle:Compound2Cyp2Document c2c2d
            WHERE c2c2d.cypsMention IN (:arrayEntityName)
            ORDER BY c2c2d.relationQualifier desc

            ";

        $query = $this->_em->createQuery($sql);
        $query->setParameter("arrayEntityName", $arrayEntityName);
        return $query;

    }

    public function getCompound2Cytochrome2Relations($field, $typeOfEntity, $arrayEntityName, $source, $orderBy)
    {
        return $this->getCompound2Cytochrome2RelationsDQL($field, $typeOfEntity, $arrayEntityName, $source, $orderBy)->getResult();
    }

    public function getCompound2Cytochrome2RelationsDQL($field, $entityType, $arrayEntityName, $source, $orderBy)
    {//("hepatotoxicity","pubmed","CompoundDict",arrayEntityId)
        $valToSearch=$this->getValToSearch($field);//"i.e hepval, embval... etc"
        //We have to create a query that searchs all over the entityIds inside the $arrayEntityId
        $orderBy=$this->getOrderBy($orderBy, $valToSearch);
        if ($orderBy=="hepval" or $orderBy=="inductionScore"){
            $orderBy="inductionScore desc";
            $secondOrderBy="svmInduction";
        }elseif($orderBy=="inhibitionScore"){
            $orderBy="inhibitionScore desc";
            $secondOrderBy="svmInhibition";
        }elseif($orderBy=="metabolismScore"){
            $orderBy=="metabolismScore desc";
            $secondOrderBy="svmMetabolism";
        }elseif($orderBy=="cypsMention"){
            $orderBy=="cypsMention asc";
            $secondOrderBy="svmInduction";
        }elseif($orderBy=="patternRelation"){
            $orderBy=="patternRelation asc";
            $secondOrderBy="svmInduction";
        }elseif($orderBy=="compoundName"){
            $orderBy=="compoundName asc";
            $secondOrderBy="svmInduction";
        }elseif($orderBy=="curation"){
            $orderBy="curation desc";
            $secondOrderBy="svmInduction";
        }
        if($source=="all"){
            $sql="SELECT c2c2d
            FROM EtoxMicromeEntity2DocumentBundle:Compound2Cyp2Document c2c2d
            WHERE c2c2d.cypsMention IN (:arrayEntityName)
            ORDER BY c2c2d.$orderBy, c2c2d.$secondOrderBy desc
            ";
            $query = $this->_em->createQuery($sql);
            $query->setParameter("arrayEntityName", $arrayEntityName);
        }else{
            $sql="SELECT c2c2d, d
            FROM EtoxMicromeEntity2DocumentBundle:Compound2Cyp2Document c2c2d
            JOIN c2c2d.document d
            WHERE c2c2d.cypsMention IN (:arrayEntityName) AND d.kind= :source
            ORDER BY c2c2d.$orderBy, c2c2d.$secondOrderBy desc
            ";
            $query = $this->_em->createQuery($sql);
            $query->setParameter("arrayEntityName", $arrayEntityName);
            $query->setParameter("source", $source);
        }

        //We have to create a query that searchs all over the entityIds inside the $arrayEntityId
        return $query;

    }

    public function getCytochrome2CompoundRelations($field, $typeOfEntity, $arrayEntityName, $source, $orderBy)
    {
        //Same method to getCompound2CytochromeRelations but called when no cytochrome is found in order to search for Compounds... Refactor it!!!!
        return $this->getCytochrome2CompoundRelationsDQL($field, $typeOfEntity, $arrayEntityName, $source, $orderBy)->getResult();
    }

    public function getCytochrome2CompoundRelationsDQL($field, $entityType, $arrayEntityName, $source, $orderBy)
    {//("hepatotoxicity","pubmed","CompoundDict",arrayEntityId)
       $valToSearch=$this->getValToSearch($field);//"i.e hepval, embval... etc"
        //We have to create a query that searchs all over the entityIds inside the $arrayEntityId
        $orderBy=$this->getOrderBy($orderBy, $valToSearch);
        if ($orderBy=="hepval" or $orderBy=="inductionScore"){
            $orderBy="inductionScore desc";
            $secondOrderBy="svmInduction";
        }elseif($orderBy=="inhibitionScore"){
            $orderBy="inhibitionScore desc";
            $secondOrderBy="svmInhibition";
        }elseif($orderBy=="metabolismScore"){
            $orderBy=="metabolismScore desc";
            $secondOrderBy="svmMetabolism";
        }elseif($orderBy=="cypsMention"){
            $orderBy=="cypsMention asc";
            $secondOrderBy="svmInduction";
        }elseif($orderBy=="patternRelation"){
            $orderBy=="patternRelation asc";
            $secondOrderBy="svmInduction";
        }elseif($orderBy=="compoundName"){
            $orderBy=="compoundName asc";
            $secondOrderBy="svmInduction";
        }elseif($orderBy=="curation"){
            $orderBy="curation desc";
            $secondOrderBy="svmInduction";
        }

        if($source=="all"){
            $sql="SELECT c2c2d
            FROM EtoxMicromeEntity2DocumentBundle:Compound2Cyp2Document c2c2d
            WHERE c2c2d.compoundName IN (:arrayEntityName)
            ORDER BY c2c2d.$orderBy, c2c2d.$secondOrderBy desc
            ";
            $query = $this->_em->createQuery($sql);
            $query->setParameter("arrayEntityName", $arrayEntityName);
        }else{
            $sql="SELECT c2c2d, d
            FROM EtoxMicromeEntity2DocumentBundle:Compound2Cyp2Document c2c2d
            JOIN c2c2d.document d
            WHERE c2c2d.compoundName IN (:arrayEntityName) AND d.kind= :source
            ORDER BY c2c2d.$orderBy, c2c2d.$secondOrderBy desc
            ";
            $query = $this->_em->createQuery($sql);
            $query->setParameter("arrayEntityName", $arrayEntityName);
            $query->setParameter("source", $source);
        }

        //We have to create a query that searchs all over the entityIds inside the $arrayEntityId
        return $query;

    }

    public function getCompound2Marker2DocumentFromField($field, $typeOfEntity, $arrayEntityName)
    {
        return $this->getCompound2Marker2DocumentFromFieldDQL($field, $typeOfEntity, $arrayEntityName)->getResult();
    }

    public function getCompound2Marker2DocumentFromFieldDQL($field, $entityType, $arrayEntityName)
    {//("hepatotoxicity","pubmed","CompoundDict",arrayEntityId)
        $valToSearch=$this->getValToSearch($field);//"i.e hepval, embval... etc"
        //We have to create a query that searchs all over the entityIds inside the $arrayEntityId
        $sql="SELECT c2m2d
            FROM EtoxMicromeEntity2DocumentBundle:Compound2Marker2Document c2m2d
            WHERE c2m2d.liverMarkerName IN (:arrayEntityName)
            ORDER BY c2m2d.relationScore desc, c2m2d.relationType desc

            ";

        $query = $this->_em->createQuery($sql);
        $query->setParameter("arrayEntityName", $arrayEntityName);
        return $query;

    }

    public function getCompound2MarkerRelations($field, $typeOfEntity, $arrayEntityName, $source, $orderBy)
    {
        return $this->getCompound2MarkerRelationsDQL($field, $typeOfEntity, $arrayEntityName, $source, $orderBy)->getResult();
    }


    public function getCompound2MarkerRelationsDQL($field, $entityType, $arrayEntityName, $source, $orderBy)
    {//("hepatotoxicity","pubmed","CompoundDict",arrayEntityId)
        $valToSearch=$this->getValToSearch($field);//"i.e hepval, embval... etc"
        //We have to create a query that searchs all over the entityIds inside the $arrayEntityId
        $orderBy=$this->getOrderBy($orderBy, $valToSearch);
        if ($orderBy=="hepval" or $orderBy=="relationScore"){
            $orderBy="relationScore DESC";
        }elseif($orderBy=="liverMarkerName"){
            $orderBy="liverMarkerName ASC";
        }elseif($orderBy=="relationType"){
            $orderBy="relationType ASC";
        }elseif($orderBy=="relationQualifier"){
            $orderBy="relationQualifier ASC";
        }elseif($orderBy=="curation"){
            $orderBy="curation desc";
        }
        if($source=="all"){
            $sql="SELECT c2m2d
            FROM EtoxMicromeEntity2DocumentBundle:Compound2Marker2Document c2m2d
            WHERE c2m2d.liverMarkerName IN (:arrayEntityName)
            ORDER BY c2m2d.$orderBy
            ";
            $query = $this->_em->createQuery($sql);
            $query->setParameter("arrayEntityName", $arrayEntityName);
        }else{
            $sql="SELECT c2m2d, d
            FROM EtoxMicromeEntity2DocumentBundle:Compound2Marker2Document c2m2d
            JOIN c2m2d.document d
            WHERE c2m2d.liverMarkerName IN (:arrayEntityName) and d.kind=:source
            ORDER BY c2m2d.$orderBy
            ";
            $query = $this->_em->createQuery($sql);
            $query->setParameter("arrayEntityName", $arrayEntityName);
            $query->setParameter("source", $source);
        }
        return $query;
    }

    public function getMarker2CompoundRelations($field, $typeOfEntity, $arrayEntityName, $source, $orderBy)
    {
        //Same method to getCompound2MarkerRelations but called when no marker is found in order to search for Compounds... Refactor it!!!!
        return $this->getMarker2CompoundRelationsDQL($field, $typeOfEntity, $arrayEntityName, $source, $orderBy)->getResult();
    }


    public function getMarker2CompoundRelationsDQL($field, $entityType, $arrayEntityName, $source, $orderBy)
    {//("hepatotoxicity","pubmed","CompoundDict",arrayEntityId)
        $valToSearch=$this->getValToSearch($field);//"i.e hepval, embval... etc"
        //We have to create a query that searchs all over the entityIds inside the $arrayEntityId
        $orderBy=$this->getOrderBy($orderBy, $valToSearch);
        if ($orderBy=="hepval" or $orderBy=="relationScore"){
            $orderBy="relationScore DESC";
        }elseif($orderBy=="liverMarkerName"){
            $orderBy="liverMarkerName ASC";
        }elseif($orderBy=="relationType"){
            $orderBy="relationType ASC";
        }elseif($orderBy=="relationQualifier"){
            $orderBy="relationQualifier ASC";
        }elseif($orderBy=="curation"){
            $orderBy="curation desc";
        }
        if($source=="all"){
            $sql="SELECT c2m2d
            FROM EtoxMicromeEntity2DocumentBundle:Compound2Marker2Document c2m2d
            WHERE c2m2d.compoundName IN (:arrayEntityName)
            ORDER BY c2m2d.$orderBy
            ";
            $query = $this->_em->createQuery($sql);
            $query->setParameter("arrayEntityName", $arrayEntityName);
        }else{
            $sql="SELECT c2m2d, d
            FROM EtoxMicromeEntity2DocumentBundle:Compound2Marker2Document c2m2d
            JOIN c2m2d.document d
            WHERE c2m2d.compoundName IN (:arrayEntityName) and d.kind=:source
            ORDER BY c2m2d.$orderBy
            ";
            $query = $this->_em->createQuery($sql);
            $query->setParameter("arrayEntityName", $arrayEntityName);
            $query->setParameter("source", $source);
        }
        return $query;
    }

    public function getEntity2DocumentElastica($field, $entityType, $arrayEntityName, $orderBy)
    {//("hepatotoxicity","pubmed","CompoundDict",arrayEntityId)
        $valToSearch=$this->getValToSearch($field);//"i.e hepval, embval... etc"
        //We have to create a query that searchs all over the entityIds inside the $arrayEntityId
        $orderBy=$this->getOrderBy($orderBy, $valToSearch);

    }

    public function findEntity2DocumentFromDocument($document)
    {
        //Function to search all the entities involved in a particular sentence in order to highlight them
        $documentId=$document->getId();

        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT e2d
            FROM EtoxMicromeEntity2DocumentBundle:Entity2Document e2d
            WHERE e2d.document = :documentId
        ');
        $consulta->setParameter('documentId', $documentId);
        return $consulta->execute();
    }

    public function getExportQuery()
    {
        //We have to create a query that searchs all over the entityIds inside the $arrayEntityId
        $sql="SELECT e2d,d
            FROM EtoxMicromeEntity2DocumentBundle:Entity2Document e2d
            JOIN e2d.document d
            WHERE e2d.qualifier = 'CompoundMesh'
            AND d.hepval is not NULL
            ORDER BY d.hepval desc
            ";

        $query = $this->_em->createQuery($sql);
        return $query;
    }

    public function updateEntity2DocumentCuration($entity2DocumentId, $action)
    {
        /*Here we get the entity2Document and the action to take for the curation value.
        $action can be check or cross.
        If $action==check, then we have to add one to the curation field of the Entity2Document register
        If $action==cross, then we have to substract one to the curation field of the Entity2Document register

        After that, taking into account the curation value, we have to generate the html to render inside the curation
        */

        //ld($entity2DocumentId);
        //ldd($action);

        $em = $this->getEntityManager();
        $entity2Document=$em->getRepository('EtoxMicromeEntity2DocumentBundle:Entity2Document')->findOneById($entity2DocumentId);
        if (!$entity2Document) {
            throw $this->createNotFoundException(
                "Cannot curate this Entity2Document $entity2DocumentId"
            );
        }
        else{
            $curation=$entity2Document->getCuration();
            if ($action=="check"){
                $entity2Document->setCuration($curation + 1);
            }elseif($action=="cross"){
                $entity2Document->setCuration($curation - 1);
            }
            $em->flush();
            $curationReturn=$entity2Document->getCuration();
            return($curationReturn);
        }
        return ($curationReturn);
    }

    public function getEntitySummary($entity2DocumentId, $qualifier){
        $em = $this->getEntityManager();
        $dictionary=array();
        $stringOutput="";

        if ($qualifier=="CompoundDict"){
            $entity2Document=$em->getRepository('EtoxMicromeEntity2DocumentBundle:Entity2Document')->findOneById($entity2DocumentId);
            $nameEntity=$entity2Document->getName();
            $entity=$em->getRepository("EtoxMicromeEntityBundle:CompoundDict")->findOneByName($nameEntity);
            if ($entity!=null){
                //Once we have the entity itself we have to create a dictionary to save with key=field, value=field_value which can be processed to create the string to the mouseover
                $name=$entity->getName();
                if($name!=""){
                    $dictionary["name"]=$name;
                }
                $chemIdPlus=$entity->getChemIdPlus();
                if($chemIdPlus!=""){
                    $dictionary["chemIdPlus"]=$chemIdPlus;
                }
                $chebi=$entity->getChebi();
                if($chebi!=""){
                    $dictionary["chebi"]=$chebi;
                }
                $inChi=$entity->getInChi();
                if($inChi!=""){
                    $dictionary["inChi"]=$inChi;
                }
                $drugBank=$entity->getDrugBank();
                if($drugBank!=""){
                    $dictionary["drugBank"]=$drugBank;
                }
                $humanMetabolome=$entity->getHumanMetabolome();
                if($humanMetabolome!=""){
                    $dictionary["humanMetabolome"]=$humanMetabolome;
                }
                $keggCompound=$entity->getKeggCompound();
                if($keggCompound!=""){
                    $dictionary["keggCompound"]=$keggCompound;
                }
                $keggDrug=$entity->getKeggDrug();
                if($keggDrug!=""){
                    $dictionary["keggDrug"]=$keggDrug;
                }
                $mesh=$entity->getMesh();
                if($mesh!=""){
                    $dictionary["mesh"]=$mesh;
                }
                $nrDbIds=$entity->getNrDbIds();
                if($nrDbIds!=""){
                    $dictionary["nrDbIds"]=$nrDbIds;
                }
                $smile=$entity->getSmile();
                if($smile!=""){
                    $dictionary["smile"]=$smile;
                }
            }
        }

        if($qualifier=="Marker"){
            $entity2Document=$em->getRepository('EtoxMicromeEntity2DocumentBundle:Entity2Document')->findOneById($entity2DocumentId);
            $nameEntity=$entity2Document->getName();
            $entity=$em->getRepository("EtoxMicromeEntityBundle:Marker")->findOneByName($nameEntity);
            //Once we have the entity itself we have to create a dictionary to save with key=field, value=field_value which can be processed to create the string to the mouseover
            if($entity!=null){
                $name=$entity->getName();
                if($name!=""){
                    $dictionary["name"]=$name;
                }
                $tax=$entity->getTax();
                if($tax!=""){
                    $dictionary["tax"]=$tax;
                }
                $markerType=$entity->getMarkerType();
                if($markerType!=""){
                    $dictionary["markerType"]=$markerType;
                }
            }
        }

        if($qualifier=="Specie"){
            $entity2Document=$em->getRepository('EtoxMicromeEntity2DocumentBundle:Entity2Document')->findOneById($entity2DocumentId);
            $nameEntity=$entity2Document->getName();
            $entity=$em->getRepository("EtoxMicromeEntityBundle:Specie")->findOneByName($nameEntity);
            //Once we have the entity itself we have to create a dictionary to save with key=field, value=field_value which can be processed to create the string to the mouseover
            if ($entity!=null){
                $name=$entity->getName();
                if($name!=""){
                    $dictionary["name"]=$name;
                }
                $nameClass=$entity->getNameClass();
                if($nameClass!=""){
                    $dictionary["nameClass"]=$nameClass;
                }
                $ncbiTaxId=$entity->getNcbiTaxId();
                if($ncbiTaxId!=""){
                    $dictionary["NCBItaxId"]=$ncbiTaxId;
                }
                $specieCategory=$entity->getSpecieCategory();
                if($specieCategory!=""){
                    $dictionary["specieCategory"]=$specieCategory;
                }
                $specieTox=$entity->getSpecieTox();
                if($specieTox!=""){
                    $dictionary["specieTox"]=$specieTox;
                }
            }

        }

        if($qualifier=="HepKeywordTermNorm"){
            $term2Document=$em->getRepository('EtoxMicromeEntity2DocumentBundle:HepKeywordTermNorm2Document')->findOneById($entity2DocumentId);
            //Once we have the entity itself we have to create a dictionary to save with key=field, value=field_value which can be processed to create the string to the mouseover
            if($term2Document!=null){
                $normalizedTerm=$term2Document->getHepKeywordNorm();
                if($normalizedTerm!=""){
                    $dictionary["Normalized Term"]=$normalizedTerm;
                }
                $kind=$term2Document->getKind();
                if($kind!=""){
                    $dictionary["kind"]=$kind;
                }
            }
        }

        if($qualifier=="HepKeywordTermVariant"){
            //ld($entity2DocumentId);
            $term2Document=$em->getRepository('EtoxMicromeEntity2DocumentBundle:HepKeywordTermVariant2Document')->findOneById($entity2DocumentId);
            //Once we have the entity itself we have to create a dictionary to save with key=field, value=field_value which can be processed to create the string to the mouseover
            //ld($term2Document);
            if($term2Document!=null){
                $term=$term2Document->getTermVariant();
                //ld($term);
                //Now we search the term in the hepatotoxkeyword table getEntityFromName
                $term = $em->getRepository('EtoxMicromeEntityBundle:HepatotoxKeyword')->getEntityFromName($term);
                if (count($term)!=0){
                    if($term!=""){
                        $dictionary["term"]=$term->getTerm();
                    }
                    $normalizedTerm=$term->getNorm();
                    if($normalizedTerm!=""){
                        $dictionary["Normalized Term"]=$normalizedTerm;
                    }
                    $pos=$term->getPos();
                    if($pos!=""){
                        $dictionary["Pos"]=$pos;
                    }
                    $efpia=$term->getEFPIA();
                    if($efpia!=""){
                        $dictionary["EFPIA"]=$efpia;
                    }
                    $costart=$term->getCOSTART();
                    if($costart!=""){
                        $dictionary["COSTART"]=$costart;
                    }
                    $meddra=$term->getMedDRA();
                    if($meddra!=""){
                        $dictionary["MedDRA"]=$meddra;
                    }
                    $mpheno=$term->getMPheno();
                    if($mpheno!=""){
                        $dictionary["MPheno"]=$mpheno;
                    }
                    $adverseEvents=$term->getAdverseEvents();
                    if($adverseEvents!=""){
                        $dictionary["Adverse Events"]=$adverseEvents;
                    }
                    $do=$term->getDo();
                    if($do!=""){
                        $dictionary["Do"]=$do;
                    }

                    $gemina_symptom=$term->getGeminaSymptom();
                    if($gemina_symptom!=""){
                        $dictionary["Gemina Symptom"]=$gemina_symptom;
                    }
                    $human_phenotype=$term->getHumanPhenotype();
                    if($human_phenotype!=""){
                        $dictionary["Human Phenotype"]=$human_phenotype;
                    }
                    $mpath=$term->getMpath();
                    if($mpath!=""){
                        $dictionary["Mpath"]=$mpath;
                    }
                    $etox=$term->getEtox();
                    if($etox!=""){
                        $dictionary["Etox"]=$etox;
                    }

                    $mesh_omim=$term->getMESH_OMIM();
                    if($mesh_omim!=""){
                        $dictionary["MESH_OMIM"]=$mesh_omim;
                    }

                    $polysearch=$term->getPolysearch();
                    if($polysearch!=""){
                        $dictionary["Polysearch"]=$polysearch;
                    }
                }
            }
        }

        if($qualifier=="Cytochrome"){
            $addWarning=false;
            $addAmbigous=false;
            $message="getEntitySummary for cytochrome";
            $cytochrome2Document=$em->getRepository('EtoxMicromeEntity2DocumentBundle:Cytochrome2Document')->findOneById($entity2DocumentId);
            //ld($cytochrome2Document);
            if ($cytochrome2Document!=null){
                $cytochromeName=$cytochrome2Document->getCypsMention();
                //ld($cytochromeName);
                $cytochrome=$em->getRepository('EtoxMicromeEntityBundle:Cytochrome')->findOneByName($cytochromeName);
                //ld($cytochrome);
                //First we search inside the cytochrome_dictionary for the name if nothing is found we search for the canonical: In both cases we end up with a list of accessions
                $arraycytochromes=$em->getRepository('EtoxMicromeEntityBundle:Cytochrome')->findByName($cytochromeName);
                //ld($arraycytochromes);
                if(count($arraycytochromes)==0){
                    $arraycytochromes=$em->getRepository('EtoxMicromeEntityBundle:Cytochrome')->findByCanonical($cytochromeName);
                }
                $arrayTaxIds=array();
                foreach($arraycytochromes as $cytochrome){
                    $arrayTaxIds[]=$cytochrome->getTax();
                }
                //ld($arrayTaxIds);



                //Now we have to search the taxId comentioned inside this sentence:
                $documentId=$cytochrome2Document->getDocument()->getId();
                $specie2documentArray=$em->getRepository('EtoxMicromeEntity2DocumentBundle:Specie2Document')->findByDocument($documentId);
                if(count($specie2documentArray)==0){
                    $ncbiTaxId=9606;//Homo sapiens
                }elseif(count($specie2documentArray)==1){
                    $specie2Document=$specie2documentArray[0];
                    $ncbiTaxId=$specie2Document->getSpecie()->getNcbiTaxId();
                    //Buscar si este ncbiTaxId se encuentra entre los taxid del array de cytochromes. Si existe lo seleccionamos. Si no existe seleccionamos humanos y añadimos warning. Mas adelante usaremos un web-service para recoger el mejor resultado de swissprot (o un outlink)
                    $ncbiTaxIdIsInArray=$em->getRepository('EtoxMicromeEntityBundle:Cytochrome')->taxIdIsInArray($ncbiTaxId, $arraycytochromes);
                    if($ncbiTaxIdIsInArray==false){
                        $ncbiTaxId=9606;//Homo sapiens
                        $addWarning=true;
                    }
                }else{
                    //If there are more than one taxId we choose the
                    if (count($arraycytochromes)==0){
                        $ncbiTaxId=9606;
                        $addWarning=true;
                    }else{
                        $arrayCytochromesSortedByRanking=$em->getRepository('EtoxMicromeEntity2DocumentBundle:Specie2Document')->getBetterRanked($arraycytochromes);
                        //ld($arrayCytochromesSortedByRanking);
                        $bestMatch=$arrayCytochromesSortedByRanking[0];
                        $ncbiTaxId=$bestMatch->getTax();
                        $stringAmbiguos="";
                        $counter=1;
                        foreach($arrayCytochromesSortedByRanking as $cytochromeSorted){
                            if($counter!=1){
                                $accession=$cytochromeSorted->getEntityId();
                                $stringAmbiguos=$stringAmbiguos . "<a href='http://www.uniprot.org/uniprot/$accession' target='_blank'> $accession</a>,";
                            }
                            $counter++;
                        }
                        $addAmbigous=true;
                    }
                    //We return the first $ncbiTaxId from the sorted array which is the taxId for the accession with the biggest ranking. Also return a field with key "Ambigous: list of accessions linked to http://www.uniprot.org/uniprot/accessionNumber "


                }




                if ($cytochrome!=null){
                    $entityId=$cytochrome->getEntityId();
                    if($entityId!=""){
                        $dictionary["Uniprot Ac."]="<a href='http://www.uniprot.org/uniprot/$entityId' target='_blank'> $entityId</a>,";
                    }
                    $name=$cytochrome->getName();
                    if($name!=""){
                        $dictionary["Name"]=$name;
                    }
                    $type=$cytochrome->getType();
                    if($type!=""){
                        $dictionary["Type"]=$type;
                    }
                    $tax=$cytochrome->getTax();
                    if($tax!=""){
                        $dictionary["NCBI taxId"]=$ncbiTaxId;
                    }
                    if($addWarning){
                            $dictionary['Warning']="Potential CYPs mention and species association error!";
                    }
                    $score=$cytochrome->getScore();
                    if($score!=""){
                        $dictionary["Score"]=round($score,3);
                    }
                    $canonical=$cytochrome->getCanonical();
                    if($canonical!=""){
                        //http://bioinformatics.charite.de/supercyp/index.php?site=cyp_drug_ia#cyp=3A4
                        $sufix=substr($canonical, 3);
                        $dictionary["Canonical"]="<a href='http://bioinformatics.charite.de/supercyp/index.php?site=cyp_drug_ia#cyp=$sufix' target='_blank'> $canonical</a>";
                    }
                    if ($addAmbigous){
                        $dictionary['Ambigous']=$stringAmbiguos;
                    }
                }
            }
        }

        foreach($dictionary as $key => $value){
            if ($value!=""){
                $stringOutput=$stringOutput."<strong>$key:</strong> $value<br/>";
            }
        }
        return ($stringOutput);
    }
}