<?php

namespace EtoxMicrome\Entity2DocumentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Specie2DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Specie2DocumentRepository extends EntityRepository
{
    public function getBetterRanked($arraycytochromes, $taxId){
        //This function receives some cytochromes and sort them by the ranking of its uniprot accession, taking into account the taxId to filter them
        $message="Inside getBetterRanked";
        if($taxId!="all"){
            //We filter the arraycytochromes taking into account only the cytochromes with the taxId desired.
            $arrayTmp=array();
            foreach($arraycytochromes as $cytochrome){
                $tax=$cytochrome->getTax();
                if($tax==$taxId){
                    $arrayTmp[]=$cytochrome;
                }
            }
            $arraycytochromes=$arrayTmp;
        }
        usort($arraycytochromes, function($cyt1,$cyt2){
            $message="Inside usort cmp";
            $ranking1=$cyt1->getCypUniprotRanking();
            $ranking2=$cyt2->getCypUniprotRanking();
            if ($ranking1 == $ranking2) {
                return 0;
            }
            return ($ranking1 > $ranking2) ? -1 : 1;
        });
        return $arraycytochromes;
    }

    public function findSpecie2DocumentFromDocument($document)
    {
        //Function to search all the entities involved in a particular sentence in order to highlight them
        $documentId=$document->getId();
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT s2d
            FROM EtoxMicromeEntity2DocumentBundle:Specie2Document s2d
            WHERE s2d.document = :documentId
        ');
        $consulta->setParameter('documentId', $documentId);
        return $consulta->execute();
    }
}
