<?php

namespace EtoxMicrome\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CypsUniprotRankingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CypsUniprotRankingRepository extends EntityRepository
{
        public function findRankingByAccession($accession1){
            $message="inside findRankingByAccession";
            ldd($message);
        }
}
