<?php

namespace EtoxMicrome\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EnzymeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnzymeRepository extends EntityRepository
{
     public function getEntityFromId($entityId)
    {
        $message="Inside getEntityFromId at EnzymeRepository";
        $query = $this->_em->createQuery("
            SELECT a
            FROM EtoxMicromeEntityBundle:Enzyme a
            WHERE a.id= :entityId
        ");
        $query->setParameter('entityId', $entityId);
        $enzyme=$query->getResult();
        if(count($enzyme)==0){
            $errorMessage="There is no entity with that name ('$entityName')";
            ldd($errorMessage);
        }
        if(count($enzyme)!=1){
            $errorMessage="There are more than one entityName for '$entityName'";
            ldd($errorMessage);
        }
        //We return all the Compounds with the entityName given. By now we supose its only one entity!!!
        $entity=$enzyme[0];
        return $entity;
    }

    public function getEntityFromName($entityName)
    {
        $message="Inside getEntityFromName at EnzymeRepository";
        $query = $this->_em->createQuery("
            SELECT a
            FROM EtoxMicromeEntityBundle:Enzyme a
            WHERE a.name= :entityName
        ");
        $query->setParameter('entityName', $entityName);
        $enzyme=$query->getResult();
        if(count($enzyme)==0){
            $errorMessage="There is no entity with that name ($entityName)";
            ldd($errorMessage);
        }
        if(count($enzyme)!=1){
            $errorMessage="There are more than one entityName for '$entityName'";
            ldd($errorMessage);
        }
        //We return all the CompoundDict with the entityName given. By now we supose its only one entity!!!
        $entity=$enzyme[0];
        return $entity;
    }
}
