<?php

namespace EtoxMicrome\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrganTissueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganTissueRepository extends EntityRepository
{
    public function getEntityFromId($entityId)
    {
        $message="Inside getEntityFromId at OrganTissueRepository";
        $query = $this->_em->createQuery("
            SELECT a
            FROM EtoxMicromeEntityBundle:OrganTissue a
            WHERE a.id= :entityId
        ");
        $query->setParameter('entityId', $entityId);
        $organTissue=$query->getResult();
        if(count($organTissue)==0){
            $errorMessage="There is no entity with that name ('$entityName')";
            ldd($errorMessage);
        }
        if(count($organTissue)!=1){
            $errorMessage="There are more than one entityName for '$entityName'";
            ldd($errorMessage);
        }
        //We return all the Compounds with the entityName given. By now we supose its only one entity!!!
        $entity=$organTissue[0];
        return $entity;
    }

    public function getEntityFromName($entityName)
    {
        $message="Inside getEntityFromName at OrganTissueRepository";
        $query = $this->_em->createQuery("
            SELECT a
            FROM EtoxMicromeEntityBundle:OrganTissue a
            WHERE a.name= :entityName
        ");
        $query->setParameter('entityName', $entityName);
        $organTissue=$query->getResult();
        if(count($organTissue)==0){
            $errorMessage="There is no entity with that name ($entityName)";
            ldd($errorMessage);
        }
        if(count($organTissue)!=1){
            $errorMessage="There are more than one entityName for '$entityName'";
            ldd($errorMessage);
        }
        //We return all the CompoundDict with the entityName given. By now we supose its only one entity!!!
        $entity=$organTissue[0];
        return $entity;
    }
}
