<?php

namespace EtoxMicrome\EntityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TanimotoValuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TanimotoValuesRepository extends EntityRepository
{
	public function getCompoundsWithTanimotos($idCompound){
		$query = $this->_em->createQuery("
            SELECT tv
            FROM EtoxMicromeEntityBundle:TanimotoValues tv
            WHERE tv.compound1= :idCompound
            OR tv.compound2= :idCompound
        ");
        $query->setParameter('idCompound', $idCompound);
        $arrayTanimotos=$query->getResult();
        return $arrayTanimotos;	
    }
    public function sortArrayByTanimoto($arrayTanimotos){
    	$message="Llega aqui";
    	$arrayTmp=array();
    	//First of all we generate an array with id=idTanimotoValue, tanimoto=tanimotoValue. So we can sort it with array_multisort
    	foreach($arrayTanimotos as $tanimotoValues){
	    	$idTmp=$tanimotoValues->getId();
	    	$tanimotoTmp=$tanimotoValues->getTanimoto();
	    	$arrayTmp[$idTmp]=$tanimotoTmp;
    	}
    	arsort($arrayTmp);
    	//Then we recreate the arrayTanimotos sorted.
    	$arrayDef=array();
    	foreach($arrayTmp as $key => $val){
    		$query = $this->_em->createQuery("
	            SELECT tv
	            FROM EtoxMicromeEntityBundle:TanimotoValues tv
	            WHERE tv.id= :key
	        ");
	        $query->setParameter('key', $key);
	        $tanimotoValue=$query->getResult();
    		array_push($arrayDef,$tanimotoValue[0]);
    	}
    	//We return just the first 10 elements of the array
        return array_slice($arrayDef, 0, 10);	
    }
    
}
