<?php

namespace EtoxMicrome\DocumentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentWithMarkerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentWithMarkerRepository extends EntityRepository
{
}
